name: Build and deploy to Azure Spring Cloud

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package -DskipTests -f event-service
    - name: Build with Maven
      run: mvn package -DskipTests -f gateway
    - name: Login to Azure Spring Cloud
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Azure Spring Cloud extension
      run: az extension add -y --name spring-cloud
    - name: Deploy event-service to Azure Spring Cloud
      run: | 
        az configure --defaults group=kyliedemo
        az configure --defaults spring-cloud=superspring
        az spring-cloud app deploy --name event-service --jar-path event-service/target/demo-0.0.1-SNAPSHOT.jar
    - name: Deploy gateway to Azure Spring Cloud
      run: |
        az configure --defaults group=kyliedemo
        az configure --defaults spring-cloud=superspring
        az spring-cloud app deploy --name gateway --jar-path gateway/target/demo-0.0.1-SNAPSHOT.jar
